### ISSUE TITLE
Cannot get auth token

### ISSUE THREAD

**Issue by anqueue** [jmlgomez73/DriveMyFiles#2]
**Describe the bug**
When signing in with tinyurl/drivemyfiles, Google blocks the request.

**To Reproduce**
1. Go to https://tinyurl.com/drivemyfiles
2. Sign in with Google
3. Access block

**Expected behavior**
Request should go through, giving the user the access token

**Screenshots**
![image](https://user-images.githubusercontent.com/35087590/230646846-81758a4e-82cd-414b-be4c-ac1164022a9a.png)
![image](https://user-images.githubusercontent.com/35087590/230646897-d2ed6868-4234-4587-899f-02e0a0f5be23.png)

**Additional context**
Related developer documentation links  to: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

**Comment by shockz-offsec** [comment]
Hello, currently this is a problem that persists in the google driver client (gdrive), so being a third party software we are waiting for a solution.

**Comment by karyzan** [comment]
please have you found a solution yet? I'm getting scared of Google more and more for everyday that goes on. My life would be in shambles if I were to loose my google account for any reason. They can ban anyone for any reason whatsoever if they feel like it. It's ridiculous how much faith I have put in them. Especially with the modern way of conducting political views. I would not be surprised if we are held hostage by google in the future.
